[[target]]
name = 'windows_amd64'
goos = 'windows'
goarch = 'amd64'
cgo-enabled = true

[[source]]
packages = [
    'fyne.io/fyne/v2',
    'fyne.io/fyne/v2/app',
    'fyne.io/fyne/v2/canvas',
    'fyne.io/fyne/v2/container',
    'fyne.io/fyne/v2/data/binding',
    'fyne.io/fyne/v2/data/validation',
    'fyne.io/fyne/v2/dialog',
    'fyne.io/fyne/v2/driver',
    'fyne.io/fyne/v2/driver/desktop',
    'fyne.io/fyne/v2/driver/mobile',
    'fyne.io/fyne/v2/driver/software',
    'fyne.io/fyne/v2/lang',
    'fyne.io/fyne/v2/layout',
    'fyne.io/fyne/v2/storage',
    'fyne.io/fyne/v2/storage/repository',
    'fyne.io/fyne/v2/test',
    'fyne.io/fyne/v2/theme',
    'fyne.io/fyne/v2/tools/playground',
    'fyne.io/fyne/v2/widget',
]